=== mlopezceliz/jsonschema_test/jschema/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "entity": {
            "type": "string"
        },
        "id": {
            "type": "string"
        },
        "metrics": {
            "type": "object",
            "properties": {
                "handling_time": {
                    "type": "object",
                    "properties": {
                        "date_from": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "estimated_days": {
                            "type": "integer"
                        },
                        "estimated_working_days": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "date_from"
                   
                    ],
                    "dependencies": {
                        "estimated_days" : ["estimated_working_days"]
                    }
                },
                "lead_time": {
                    "type": "object",
                    "properties": {
                        "estimated_days": {
                            "type": "integer"
                        },
                        "shipping_offset_days": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "estimated_days",
                        "shipping_offset_days"
                    ]
                }
            },
            "required": [
                "handling_time",
                "lead_time"
            ]
        },
        "version": {
            "type": "string"
        }
    },
    "required": [
        "entity",
        "id",
        "metrics",
        "version"
    ]
}

=== mlopezceliz/jsonschema_test/document.json
{
    "entity": "SHIPMENT_TEST",
    "id": "28128153121",
    "metrics": {
        "handling_time": {
            "date_from": "2019-10-11T13:38:29-03:00",
            "estimated_days": 1,
            "estimated_working_days":3
        },
        "lead_time": {
            "estimated_days": 3,
            "shipping_offset_days": 2
        }
    },
    "version": "0.0.1"
}
